app = "TODO: TG BOT NAME"
primary_region = "fra"

[build]

[env]
  TELEGRAM_BOT_TOKEN = "TODO"
  WEBHOOK_URL = "TODO"

[http_service]
  internal_port = 8443
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
